### ISSUE TITLE
crash on npm run calling dev dependency

### ISSUE THREAD

**Issue by FallenRiteMonk** [srs/gradle-node-plugin#111]
Hy,
I have the following build.gradle file for a angular2 project of mine:
```
buildscript {
    repositories {
        jcenter()
    }
}

plugins {
  id "com.moowork.node" version "0.12"
}

node {
  version = '5.9.1'
  npmVersion = '3.9.0'
  download = true
}

task clean(type: Delete) {
  delete 'dist', 'node_modules'
}

task build()
build.dependsOn npm_run

npm_run {
  args = ['build']
}
npm_run.dependsOn npmInstall
```
my package.json  has the following script defined ```"build": "ng build -prod"```
with the devDependecy ```"angular-cli": "1.0.0-beta.1"```

running the build script on a ubuntu server without node and npm installed crashes when trying to run the npm build script due to the command ng not being found.

I cant give the exact error message because i had to get it up and running quickly so I installed node, npm and angular-cli on the machine, but if required I can try to reproduce!

**Comment by FallenRiteMonk** [comment]
```
> ng build -prod

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Could not require 'angular-cli-build.js': Cannot find module 'angular-cli/lib/broccoli/angular2-app'
Error: Could not require 'angular-cli-build.js': Cannot find module 'angular-cli/lib/broccoli/angular2-app'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (<ABSOLUTE_PROJECT_PATH>/angular-cli-build.js:3:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "<ABSOLUTE_PROJECT_PATH>/.gradle/nodejs/node-v5.9.1-linux-x64/bin/node" "<ABSOLUTE_PROJECT_PATH>/node_modules/npm/bin/npm-cli.js" "run" "build"
npm ERR! node v5.9.1
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! <PROJECT_NAME>@0.0.0 build: `ng build -prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the <PROJECT_NAME>@0.0.0 build script 'ng build -prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the <PROJECT_NAME> package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build -prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs <PROJECT_NAME>
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls <PROJECT_NAME>
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     <ABSOLUTE_PROJECT_PATH>/npm-debug.log
:web-client:npm_run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':web-client:npm_run'.
> Process 'command '<ABSOLUTE_PROJECT_PATH>/.gradle/nodejs/node-v5.9.1-linux-x64/bin/node'' finished with non-zero exit value 1

```

**Comment by srs** [comment]
Do you have any project on GitHub I could try it on? Not familiar with angular so it's a little difficult to recreate the project.

**Comment by chenrui333** [comment]
I dont think this issue has anything to do with Angular
