### ISSUE TITLE
yarn_install task failed on Windows 10

### ISSUE THREAD

**Issue by kucharzyk** [srs/gradle-node-plugin#182]
Yarn install is failing on windows 10.

It can't find file 
```
build\yarn\node_modules\yarn\node_modules\bl\node_modules\readable-stream\duplex.js
```

File exists in diffenent localization
```
build\yarn\node_modules\yarn\node_modules\readable-stream\duplex.js
```

*The same setup works on linux*

```
C:\DEV\GITHUB\shardis\build\yarn\node_modules\yarn\bin\yarn.js:62
      throw err;
      ^

Error: ENOENT: no such file or directory, open 'C:\DEV\GITHUB\shardis\build\yarn\node_modules\yarn\node_modules\bl\node_modules\readable-stream\duplex.js'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\DEV\GITHUB\shardis\build\yarn\node_modules\yarn\node_modules\bl\bl.js:1:82)
    at Module._compile (module.js:571:32)
:yarn_install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':yarn_install'.
> Process 'command 'C:\DEV\GITHUB\shardis\build\nodejs\node-v7.3.0-win-x64\node.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.74 secs
```

My gradle config:
```
 gradleNodePluginVersion = "1.0.1"

node {
  version = "7.3.0"
  npmVersion = "4.0.5"
  yarnVersion = "0.18.1"
  download = true
  workDir = file("${project.buildDir}/nodejs")
  npmWorkDir = file("${project.buildDir}/npm")
  yarnWorkDir = file("${project.buildDir}/yarn")
  nodeModulesDir = file("${project.projectDir}")
}
```
https://github.com/shardis/shardis/blob/master/build.gradle

**Comment by kucharzyk** [comment]
Problem is related to new flat npm structure.

I've specified npm version as 4.0.5 and install failed.

If i remove npmVersion declatarion npm version used is 3.10.10 and yarn_install works well.


I have no idea why npm 4.0.5 works well on linux but is failing on windows

**Comment by kucharzyk** [comment]
I think that pull request #186 should fix this issue
