### ISSUE TITLE
gradle npmInstall throws error

### ISSUE THREAD

**Issue by shgattu** [srs/gradle-node-plugin#239]
Hi,
I see below error when I run gradle npmInstall. Any help will be really appreciated.
Module.js:339
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /node-v4.2.1-linux-x64/lib/node_modules/npm/bin/npm-cli.js:19:11
    at Object.<anonymous> (/node-v4.2.1-linux-x64/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
:microservices:orchestrator-micro:npmSetup FAILED

**Comment by shgattu** [comment]
This was an internal node version issue. This is fixed now.
