### ISSUE TITLE
Update to version 1.2.0 works on Linux, fails on Windows

### ISSUE THREAD

**Issue by daelfdude** [srs/gradle-node-plugin#244]
I recently attempted to update the version of both the node and gulp plugins-to-gradle, but found that it broke the build on Windows (though it continued working on Linux) when I did.  I looked through the existing Issue List (as well as the documentation) but didn't recognize anything speaking to my situation.  The details of what I'm seeing are below.

**Gradle version:** 
 3.5 (same behavior for 4.0.1)

**Command line:**
 C:\Dev\git\app>.\gradlew -Penvironment=qa --stacktrace clean cleanNode assemble 

**configuration snippet:**
 node {
    version         '5.8.0'
    npmVersion      '3.8.0'
    distBaseUrl     'https://nodejs.org/dist'
    download        true
    workDir         file("${project.clientappDir}/nodebin")
    nodeModulesDir  file(project.clientappDir)
 }

 task cleanNode(type: Delete) {
    delete "${project.clientappDir}/node_modules"
    delete "${project.clientappDir}/nodebin"
 }

 task gulpBuild(type: GulpTask, dependsOn: ['npmInstall','installGulp']) {
    doFirst {
        println ' starting gulp on node'
    }
    args = ['build']
 }

 war {
    dependsOn gulpBuild
    ....
 }
**Plugin versions which work:**
 id "com.moowork.node"              version "1.1.1"
 id "com.moowork.gulp"              version "0.13"

**Plugin versions which fail:**
 id "com.moowork.node"              version "1.2.0"
 id "com.moowork.gulp"              version "1.2.0"

**Output snippet when failing:** 
> Task :caisx:npmSetup
'node' is not recognized as an internal or external command,
operable program or batch file.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':caisx:npmSetup'.
> Process 'command 'C:\Dev\git\app\CAIS2.0\.gradle\npm\npm-v3.8.0\npm.cmd'' fini
shed with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':caisx:n
pmSetup'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingState
Executer.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskE
xecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.ex
ecute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu
ildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu
ildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(De
faultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo
rker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo
rker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo
rker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo
rker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(Defau
ltTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTa
sk(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWo
rker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
xecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnabl
e.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Dev\g
it\app\CAIS2.0\.gradle\npm\npm-v3.8.0\npm.cmd'' finished with non-zero exit valu
e 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
rmalExitValue(DefaultExecHandle.java:370)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecActi
on.java:31)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOp
erations.java:182)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.ja
va:1071)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.ja
va:1066)
        at org.gradle.api.Project$exec$3.call(Unknown Source)
        at com.moowork.gradle.node.exec.ExecRunner.run(ExecRunner.groovy:37)
        at com.moowork.gradle.node.npm.NpmExecRunner.doExecute(NpmExecRunner.gro
ovy:55)
        at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:63)
        at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
        at com.moowork.gradle.node.npm.NpmSetupTask.exec(NpmSetupTask.groovy:104
)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore
$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore
$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore
$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:711)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.
run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu
ildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu
ildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(De
faultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more

view of folder referenced in error message
![image](https://user-images.githubusercontent.com/13697292/28220979-1f8d5be2-6887-11e7-9ae3-f9cc7619604a.png)

**Comment by srs** [comment]
Thanks for reporting. Marking this as a bug.

**Comment by Albert-Gao** [comment]
Any updates on this?
Got this error too.
