### ISSUE TITLE
Node plugin doesn't work wit Gradle 4.10.1

### ISSUE THREAD

**Issue by bp91** [srs/gradle-node-plugin#309]
After upgrade Gradle to 4.10.1 version, Node plugin stopped working. When I run **gradle npm_install** I receive the following output:

```
gradle npm_install --info
Initialized native services in: /home/bruno/.gradle/native
The client will now receive all logging from the daemon (pid: 28355). The daemon log file: /home/bruno/.gradle/daemon/4.10.1/daemon-28355.out.log
Starting 29th build in daemon [uptime: 16 mins 39.111 secs, performance: 99%]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/home/bruno/development/private/gradle-springboot-jersey/testwebapp/settings.gradle'.
Projects loaded. Root project using build file '/home/bruno/development/private/gradle-springboot-jersey/testwebapp/build.gradle'.
Included projects: [root project 'testwebapp']

> Configure project :
Evaluating root project 'testwebapp' using build file '/home/bruno/development/private/gradle-springboot-jersey/testwebapp/build.gradle'.
Applying dependency management to configuration 'annotationProcessor' in project 'testwebapp'
Applying dependency management to configuration 'apiElements' in project 'testwebapp'
Applying dependency management to configuration 'archives' in project 'testwebapp'
Applying dependency management to configuration 'bootArchives' in project 'testwebapp'
Applying dependency management to configuration 'compile' in project 'testwebapp'
Applying dependency management to configuration 'compileClasspath' in project 'testwebapp'
Applying dependency management to configuration 'compileOnly' in project 'testwebapp'
Applying dependency management to configuration 'default' in project 'testwebapp'
Applying dependency management to configuration 'implementation' in project 'testwebapp'
Applying dependency management to configuration 'runtime' in project 'testwebapp'
Applying dependency management to configuration 'runtimeClasspath' in project 'testwebapp'
Applying dependency management to configuration 'runtimeElements' in project 'testwebapp'
Applying dependency management to configuration 'runtimeOnly' in project 'testwebapp'
Applying dependency management to configuration 'testAnnotationProcessor' in project 'testwebapp'
Applying dependency management to configuration 'testCompile' in project 'testwebapp'
Applying dependency management to configuration 'testCompileClasspath' in project 'testwebapp'
Applying dependency management to configuration 'testCompileOnly' in project 'testwebapp'
Applying dependency management to configuration 'testImplementation' in project 'testwebapp'
Applying dependency management to configuration 'testRuntime' in project 'testwebapp'
Applying dependency management to configuration 'testRuntimeClasspath' in project 'testwebapp'
Applying dependency management to configuration 'testRuntimeOnly' in project 'testwebapp'
Applying dependency management to configuration 'providedCompile' in project 'testwebapp'
Applying dependency management to configuration 'providedRuntime' in project 'testwebapp'
All projects evaluated.
Selected primary task 'npm_install' from project :
Tasks to be executed: [task ':nodeSetup', task ':npmSetup', task ':npm_install']
:nodeSetup (Thread[Task worker for ':',5,main]) started.

> Task :nodeSetup SKIPPED
Skipping task ':nodeSetup' as task onlyIf is false.
:nodeSetup (Thread[Task worker for ':',5,main]) completed. Took 0.004 secs.
:npmSetup (Thread[Task worker for ':',5,main]) started.

> Task :npmSetup SKIPPED
Skipping task ':npmSetup' as task onlyIf is false.
:npmSetup (Thread[Task worker for ':',5,main]) completed. Took 0.0 secs.
:npm_install (Thread[Task worker for ':',5,main]) started.

> Task :npm_install FAILED
Task ':npm_install' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'npm''. Working directory: /home/bruno/development/private/gradle-springboot-jersey/testwebapp Command: npm install
:npm_install (Thread[Task worker for ':',5,main]) completed. Took 0.003 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npm_install'.
> A problem occurred starting process 'command 'npm''

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

Also after running gradle bootRun I receive the same output.

My builld.gradle file is:

```
buildscript {
	// configurations {
    //     classpath {
    //         exclude group: 'ch.qos.logback', module: 'logback-classic'
	// 		exclude group: 'org.slf4j'
	// 		exclude group: 'log4j', module: 'log4j'
    //     }
    // }
	ext {
		springBootVersion = '2.0.5.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

plugins {
  id "com.moowork.node" version "1.2.0"
  id "com.moowork.grunt" version "1.2.0"
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'eclipse-wtp'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'war'

group = 'it'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}

configurations {
	providedRuntime
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter-jersey')
	compile('org.mybatis.spring.boot:mybatis-spring-boot-starter:1.3.2')
	compile group: 'org.glassfish.jersey.media', name: 'jersey-media-multipart', version: '2.27'
	compile group: 'org.springframework', name: 'spring-web', version: '5.0.9.RELEASE'
	compile group: 'com.google.guava', name: 'guava', version: '26.0-jre'
	compile group: 'mysql', name: 'mysql-connector-java', version: '8.0.12'
	compile group: 'org.springframework.boot', name: 'spring-boot-devtools', version: '2.0.5.RELEASE'
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-rest', version: '2.0.5.RELEASE'
	compile('org.springframework.boot:spring-boot-starter-web')
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-tomcat', version: '2.0.5.RELEASE'
	compile group: 'org.springframework.boot', name: 'spring-boot-starter-thymeleaf', version: '2.0.5.RELEASE'
	compile group: 'org.postgresql', name: 'postgresql', version: '42.2.5'
	providedRuntime('org.springframework.boot:spring-boot-starter-tomcat')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

bootRun {
	dependsOn 'gruntExec'
}

task gruntExec(type: Exec) {
	dependsOn 'installNpm'
	
	commandLine 'grunt', 'build'
}

task installNpm(type: Exec) {
	commandLine 'npm', 'install'
}
```
Anyone can help me? Thanks for the support

**Comment by IamTechknow** [comment]
I just upgraded to gradle 4.10.2 from 4.4, and this plugin still works for me (and a little faster, which is nice).

Here is my [build.gradle file](https://github.com/IamTechknow/d2sbackend/blob/master/build.gradle)

**Comment by abendt** [comment]
I think we also ran into the issue while trying to upgrade a project from spring boot 1.x to 2.x. I could narrow it down to the combination of gradle, version of the node plugin and the version of the spring boot plugin we are using:

* the issue only occurs when gradle 4.10 and spring boot 2.0.5 are used
* gradle 4.9 works with spring boot 2
* gradle 4.10 only works with spring boot 1

i have created an stripped down example project here:
https://github.com/abendt/gradle-node-bug

```
git checkout https://github.com/abendt/gradle-node-bug.git
cd gradle-node-bug
./gradlew check
```

```
$ ./gradlew  check --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':server'.
> Could not create task ':server:check'.
   > Could not create task ':server:jest'.
      > Could not create task of type 'YarnTask'.
         > Project#afterEvaluate(Closure) on project ':server' cannot be executed in the current context.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':server'.
        at org.gradle.execution.TaskNameResolver.getExistingTask(TaskNameResolver.java:116)
        at org.gradle.execution.TaskNameResolver.access$000(TaskNameResolver.java:32)
        at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collect(TaskNameResolver.java:174)
        at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collect(TaskNameResolver.java:181)
        at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collectTasks(TaskNameResolver.java:166)
        at org.gradle.execution.TaskNameResolver.selectWithName(TaskNameResolver.java:55)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:103)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:81)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraph.run(DefaultGradleLauncher.java:305)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.constructTaskGraph(DefaultGradleLauncher.java:190)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:145)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':server:check'.
        at org.gradle.api.internal.tasks.DefaultTaskContainer.taskCreationException(DefaultTaskContainer.java:673)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.access$600(DefaultTaskContainer.java:75)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider$1.run(DefaultTaskContainer.java:649)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.getOrNull(DefaultTaskContainer.java:632)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.getOrNull(DefaultTaskContainer.java:596)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.findByName(DefaultNamedDomainObjectCollection.java:279)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.findByName(DefaultTaskContainer.java:523)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.findByName(DefaultTaskContainer.java:74)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:318)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.getByName(DefaultTaskCollection.java:39)
        at org.gradle.execution.TaskNameResolver.getExistingTask(TaskNameResolver.java:114)
        ... 93 more
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':server:jest'.
        at org.gradle.api.internal.tasks.DefaultTaskContainer.taskCreationException(DefaultTaskContainer.java:673)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.access$600(DefaultTaskContainer.java:75)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider$1.run(DefaultTaskContainer.java:649)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.getOrNull(DefaultTaskContainer.java:632)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.getOrNull(DefaultTaskContainer.java:596)
        at org.gradle.api.internal.provider.AbstractProvider.get(AbstractProvider.java:28)
        at Build_gradle$3$1.invoke(build.gradle.kts:42)
        at Build_gradle$3$1.invoke(build.gradle.kts:2)
        at org.gradle.kotlin.dsl.TaskContainerExtensionsKt$sam$i$org_gradle_api_Action$0.execute(TaskContainerExtensions.kt)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator$4.execute(BuildOperationCrossProjectConfigurator.java:108)
        at org.gradle.internal.ImmutableActionSet$SetWithManyActions.execute(ImmutableActionSet.java:329)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:244)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:238)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:117)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.access$2500(DefaultTaskContainer.java:75)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider$1.run(DefaultTaskContainer.java:645)
        ... 106 more
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'YarnTask'.
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:80)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:75)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:459)
        at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:194)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.create(AnnotationProcessingTaskFactory.java:50)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.createTask(DefaultTaskContainer.java:305)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.access$200(DefaultTaskContainer.java:75)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider$1.run(DefaultTaskContainer.java:640)
        ... 124 more
Caused by: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator$IllegalCrossProjectConfigurationException: Project#afterEvaluate(Closure) on project ':server' cannot be executed in the current context.
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator.createIllegalStateException(BuildOperationCrossProjectConfigurator.java:117)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator.assertCrossProjectConfigurationAllowed(BuildOperationCrossProjectConfigurator.java:87)
        at org.gradle.api.internal.project.DefaultProject.assertMutatingMethodAllowed(DefaultProject.java:1428)
        at org.gradle.api.internal.project.DefaultProject.afterEvaluate(DefaultProject.java:1002)
        at org.gradle.api.Project$afterEvaluate$1.call(Unknown Source)
        at com.moowork.gradle.node.yarn.YarnTask.<init>(YarnTask.groovy:24)
        at com.moowork.gradle.node.yarn.YarnTask_Decorated.<init>(Unknown Source)
        at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:65)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:78)
        ... 132 more


* Get more help at https://help.gradle.org
```

**Comment by sergey-morenets** [comment]
@abendt I have similar project with Gradle 5.0 RC1, Spring Boot 2.10 and Node plugin and it builds fine.
