### ISSUE TITLE
Version issue during build

### ISSUE THREAD

**Issue by adispennette** [srs/gradle-node-plugin#358]
I am seeing the below error when trying to build using the gradle plugin.
Is there a way to update the versions of the transitive dependencies?

```
~/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: 'make' failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/gitlab/integrated-payment/payments-app/node_modules/fsevents
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 install: 'node-gyp rebuild'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 140 packages from 161 contributors and audited 1231 packages in 37.638s

6 packages are looking for funding
  run 'npm fund' for details

found 34 vulnerabilities (8 low, 7 moderate, 19 high)
  run 'npm audit fix' to fix them, or 'npm audit' for details

Task :integrated-payment:grunt_build FAILED
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.

FAILURE: Build failed with an exception.
```

**Comment by deepy** [comment]
Isn't this a pure node/npm issue? Does `npm install` on this project normally work?
