### ISSUE TITLE
Blank space in Windows user path leads to error

### ISSUE THREAD

**Issue by habecht** [srs/gradle-node-plugin#56]
Hi,
I have a blank space in my Windows user name and I am getting an error with the following stacktrace:

    Caused by: org.gradle.process.internal.ExecException: Process 'command 'cmd'' finished with non-zero exit value 1
            at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
            at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
            at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:151)
            at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:780)
            at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:776)
            at org.gradle.api.Project$exec$8.call(Unknown Source)
            at com.moowork.gradle.node.exec.ExecRunner.run(ExecRunner.groovy:43)
            at com.moowork.gradle.node.exec.NodeExecRunner.doExecute(NodeExecRunner.groovy:29)
            at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:73)
            at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)
            at com.moowork.gradle.node.exec.NpmExecRunner.doExecute(NpmExecRunner.groovy:37)
            at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.groovy:73)
            at com.moowork.gradle.node.exec.ExecRunner$execute.call(Unknown Source)

I have tried Release 0.9 and the latest 0.10-SNAPSHOT

Thanks in advance for your help!

**Comment by habecht** [comment]
Sorry, my fault. This issue is actually resolved in the latest snapshot.
