### ISSUE TITLE
My --harmony option gets quoted on Windows

### ISSUE THREAD

**Issue by davidknezic** [srs/gradle-node-plugin#72]
I have to run my gulp script with the `--harmony` flag. For that I use the following config:

```groovy
task build(type: NodeTask, dependsOn: npm_install) {
  script = file('node_modules/.bin/gulp')
  args = ['--harmony', 'build']
}
```

This works perfectly on Mac OS X and Linux. But the `--harmony` option isn't recognized as such on Windows.

After some digging, I found out that all arguments get quoted on Windows (in [ExecRunner.groovy](https://github.com/srs/gradle-node-plugin/blob/master/src/main/groovy/com/moowork/gradle/node/exec/ExecRunner.groovy)).

```groovy
73: args.each {
74:     result += '"' + it + '"'
75: }
```

**Comment by jelion** [comment]
I think I am seeing a similar problem.  I pulled this tool down to experiment with, and very quickly got it to where I could run a simple NPM test command:

```
task npm_install(type: NpmTask) {
  args = ['install', '--no-color']
}
```

"gradle npm_install" I got an error gave me an error "Cannot find module '/path/to/node/node_modules/npm/bin/npm-cli.js' with a stack dump, and the Gradle build failed.  The npm-cli.js script was in fact present.  "gradle --debug" gave me the command as <cmd /c ""npm" "install" "--no-color""> - that is, each argument was in quotes, AND the entire DOS command was quoted again.  (Angle brackets used because the double-quotes are actually part of the command.)

in my console, <cmd /c npm install --no-color> works; <cmd /c "npm -install --no-color"> works; but <cmd /c ""npm" "install" "--no-color""> gives me the same error about npm-cli.js.

I suspect this is the same error reported by David.

-----

Package version: 0.10  Node version: 0.12.7  npm version: 2.11.3 on Windows 7 Enterprise SP1

-----
```
c:\jdev\cpc-maven\try.p4.1\xforms>gradle npm_install
GRADLE_LIB='C:\jdev\cpc-maven\try.p4.1\000.gradle' (xforms)
:nodeSetup SKIPPED
:npm_install
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\jdev\cpc-maven\try.p4.1\xforms\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
:npm_install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npm_install'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 2.732 secs

c:\jdev\cpc-maven\try.p4.1\xforms>cmd /c npm install --nocolor
npm WARN package.json xforms@0.1.0 No repository field.
npm WARN package.json xforms@0.1.0 No README data
npm WARN package.json xforms@0.1.0 No license field.

c:\jdev\cpc-maven\try.p4.1\xforms>cmd /c "npm install --nocolor"
npm WARN package.json xforms@0.1.0 No repository field.
npm WARN package.json xforms@0.1.0 No README data
npm WARN package.json xforms@0.1.0 No license field.

c:\jdev\cpc-maven\try.p4.1\xforms>cmd /c ""npm" "install" "--nocolor""
module.js:338
    throw err;
          ^
Error: Cannot find module 'c:\jdev\cpc-maven\try.p4.1\xforms\node_modules\npm\bi
n\npm-cli.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

c:\jdev\cpc-maven\try.p4.1\xforms>
```

**Comment by srs** [comment]
Thanks for reporting this. So, this works?

    cmd /c "npm install --nocolor"

But, this does not?

    cmd /c ""npm" "install" "--nocolor""

**Comment by srs** [comment]
It seems that I need to implement "smarter" quoting. I am in the process of writing more integration and functional tests for this so will try to replicate it in a simple test.

**Comment by srs** [comment]
I cannot seem to get the same error as you. Can you try to replicate this problem and paste in package.json and build.gradle (and other relevant files) here?

**Comment by jelion** [comment]
You shouldn't need Gradle to reproduce the command line behavior.  I installed Node 0.12.7 just now at home just now and reproduced the behavior shown above on Windows 8.1.  That is,  I created a pretty empty package.json ("npm init" and accepted all the defaults), and then ran (here's the entire session)

```
    c:\tmp\tmp>npm init
    This utility will walk you through creating a package.json file.
    ... <snip>
    Press ^C at any time to quit.
    name: (x)
    version: (1.0.0)
    description:
    git repository:
    keywords:
    author:
    license: (ISC)
    About to write to c:\tmp\tmp\package.json:
    
    {
      "name": "x",
      "version": "1.0.0",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "description": ""
    }
    
    
    Is this ok? (yes)
    
    c:\tmp\tmp>cmd /c "npm install"
    npm WARN package.json x@1.0.0 No description
    npm WARN package.json x@1.0.0 No repository field.
    npm WARN package.json x@1.0.0 No README data
    
    c:\tmp\tmp>cmd /c "npm" "install"
    'npm" "install' is not recognized as an internal or external command,
    operable program or batch file.
    
    c:\tmp\tmp>cmd /c ""npm" "install""
    module.js:338
        throw err;
              ^
    Error: Cannot find module 'c:\tmp\tmp\node_modules\npm\bin\npm-cli.js'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
    
    c:\tmp\tmp>cmd /c """npm"" ""install"""
    module.js:338
        throw err;
              ^
    Error: Cannot find module 'c:\tmp\tmp\node_modules\npm\bin\npm-cli.js'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
    
    c:\tmp\tmp>
```

Because I can reproduce this at the command line, I don't think the Gradle stuff is relevant - the plugin code generated arguments which matched what I typed in the command lines shown above.At least with Node 0.12.7 (npm 2.11.3).  This version was released in August.

I did notice the current version is Node 4.4.1, so I tried installing that (npm 2.14.4), but I got essentially the same results - even the line numbers were the same.

Hmmm.  I do believe you're legitimately trying...  I wonder what is different?

**Comment by jelion** [comment]
For the record, my CMD is version 6.3.9600.17415, used for the post I wrote just now.  My earlier report was made from work, which has only Windows 7, and I expect an earlier build of CMD.

**Comment by srs** [comment]
Ok. Will try your examples above in Windows 8.1 to see if I can reproduce.

**Comment by srs** [comment]
You could try to add a new integration test to reproduce your problem. Added some integration tests yesterday that you can use as a base. Have also added windows CI build using AppVeyor that will build and test on Windows 2012 server.
