### ISSUE TITLE
TypeError: Request path contains unescaped characters.

### ISSUE THREAD

**Issue by franck-serot** [srs/gradle-node-plugin#88]
Hi,
I try to use the plug gradle-no-plugin on a 'helloworld' nodejs project.
I could install node but I have an strange error with npm installation of dependencies.
I noted 2 versions of node are installed : 
- build\nodejs\node-v0.11.10-linux-x86
- \\build\\nodejs\\node-v0.11.10-windows-x64

At first, I think my problem was the proxy of my company but I had already added in the file 'gradle.properties' with the proxy configuration.
I plan to reproduce this problem at home in order to suppress the company proxy.
Could you help me to understand and solve this problem ?
Best regards,
Franck

``` MSDOS

D:\workshop\veille\workspace-mars\HelloWorld-Node-Gradle>gradle clean npmInstall
:clean
:nodeSetup
:npmSetup
npm http GET https://registry.npmjs.org/npm/2.1.5
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at Agent.request (_http_agent.js:286:11)
npm ERR!     at TunnelingAgent.exports.request (https.js:129:22)
npm ERR!     at TunnelingAgent.createSocket (D:\workshop\veille\workspace-mars\HelloWorld-Node-Gradle\build\nodejs\node-v0.11.10-linux-x86\lib\node_modules\npm\
node_modules\request\node_modules\tunnel-agent\index.js:117:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (D:\workshop\veille\workspace-mars\HelloWorld-Node-Gradle\build\nodejs\node-v0.11.10-linux-x
86\lib\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (D:\workshop\veille\workspace-mars\HelloWorld-Node-Gradle\build\nodejs\node-v0.11.10-linux-x86\lib\node_modules\npm\no
de_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:125:16)
npm ERR!     at Agent.request (_http_agent.js:301:10)
npm ERR!     at Object.exports.request (https.js:129:22)
npm ERR!     at Request.start (D:\workshop\veille\workspace-mars\HelloWorld-Node-Gradle\build\nodejs\node-v0.11.10-linux-x86\lib\node_modules\npm\node_modules\r
equest\request.js:583:30)
npm ERR!     at Request.end (D:\workshop\veille\workspace-mars\HelloWorld-Node-Gradle\build\nodejs\node-v0.11.10-linux-x86\lib\node_modules\npm\node_modules\req
uest\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\workshop\\veille\\workspace-mars\\HelloWorld-Node-Gradle\\build\\nodejs\\node-v0.11.10-windows-x64\\bin\\node.exe" "D:\\workshop\\veille\\
workspace-mars\\HelloWorld-Node-Gradle\\build\\nodejs\\node-v0.11.10-linux-x86\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@2.1.5"
npm ERR! cwd D:\workshop\veille\workspace-mars\HelloWorld-Node-Gradle
npm ERR! node                                                                                                                                            -v v0.1
1.10
npm ERR! npm -v 1.3.22
                                                                                                                                                        :npmSetu
p                                                                                                                                                       FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npmSetup'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.999 secs

D:\workshop\veille\workspace-mars\HelloWorld-Node-Gradle>
```

**Comment by srs** [comment]
Hi. 

Well, I'm not sure about the problem, but could you try to run ``npm install`` without using Gradle to see what happens?

**Comment by srs** [comment]
Closing this due to inactivity.
