### ISSUE TITLE
Running .cmd scripts without using execOverrides

### ISSUE THREAD

**Issue by Jan539** [srs/gradle-node-plugin#99]
Hey, 

I want to use jspm in our project on windows so we got a task:

`
task jspmInstall(type: NodeTask, dependsOn: npmInstall) { 
        ... //some stuff
	script = file('.../jspm.cmd')
	args = [ 'install' ]
}
`

This gives a SyntaxError: Unexpected token ILLEGAL at the first line of jspm.cmd (@IF EXIST "%~dp0\node.exe"). On linux this works though (with '.../jspm'). However if I extend the task with 

`
execOverrides {
    it.executable = './node_modules/.bin/jspm'
    it.args = [ 'install', '--yes' ]
}
`
it works just fine.

Any ideas how this can be fixed without using execOverrides or why this is the case at all?

**Comment by srs** [comment]
Hi.

The first thing is that the ``NodeTask`` does not understand windows ``cmd`` format files, only javascript files. So if you set the script to the following instead, you should be fine:

    task jspmInstall(type: NodeTask, dependsOn: npmInstall) {
       script = file('./node_modules/.bin/jspm')
       args = ['install']
    }

**Comment by Jan539** [comment]
Thanks for the fast reply. With this I get syntax error in the shell script (Unexpected token 'case'). This is what works with linux but not in windows and why I tried the .cmd file. I'm new to gradle so I don't know if there is a trick to fix this.

**Comment by srs** [comment]
Also remove the exec overrides above.

**Comment by Jan539** [comment]
I'm using:
```
task jspmInstall(type: NodeTask, dependsOn: npmInstall) {
   description = 'Installs jspm packages'
   inputs.files 'package.json', 'config.js'
   outputs.dir 'jspm_packages'
   outputs.files 'config.js'
   script = file('./node_modules/.bin/jspm')
   args = ['install']
}
```
and it gives me 
```
...\node_modules\.bin\jspm:4
case `uname` in
^^^^
SyntaxError: Unexpected token case
```

**Comment by srs** [comment]
Ok. Let me test this locally. What kind of OS do you run on?

**Comment by Jan539** [comment]
Windows 7 Professional SP1

**Comment by srs** [comment]
Will check later today.

**Comment by Jan539** [comment]
Hey srs, did you already have the time to look into this issue?

**Comment by JakePi3** [comment]
bump.  Also seeing this with: 

```
task webpack(type: NodeTask, dependsOn: 'npmInstall') {
    script = project.file('node_modules/.bin/webpack')
}
```

Looks like it's a windows-specific problem with the way the node script is invoked.

```
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
:monitor-frontend:webpack FAILED
```
